# GitHub 赞助配置文件
# 这些链接将显示在 GitHub 仓库主页的“赞助”按钮旁边。

github: tukuaiai # 您的 GitHub 用户名，例如: [octocat]
# patreon: your-patreon-username # 您的 Patreon 用户名
# open_collective: your-opencollective-project-name # 您的 Open Collective 项目名称
# ko_fi: your-ko-fi-username # 您的 Ko-fi 用户名
# tidelift: # Tidelift 支持
#   - package-name/platform
#   - another-package/platform
# community_bridge: your-community-bridge-project-name # 您的 Community Bridge 项目名称
# liberapay: your-liberapay-username # 您的 Liberapay 用户名
# issuehunt: your-issuehunt-username # 您的 IssueHunt 用户名
# otechie: your-otechie-username # 您的 Otechie 用户名
custom:
  - 'https://t.me/desci0'
  - 'tron: TQtBXCSTwLFHjBqTS4rNUp7ufiGx51BRey'
  - 'sol: HjYhozVf9AQmfv7yv79xSNs6uaEU5oUk2USasYQfUYau'
  - 'eth: 0xa396923a71ee7D9480b346a17dDeEb2c0C287BBC'
  - 'bsc: 0xa396923a71ee7D9480b346a17dDeEb2c0C287BBC'
  - 'btc: bc1plslluj3zq3snpnnczplu7ywf37h89dyudqua04pz4txwh8z5z5vsre7nlm'
  - 'sui: 0xb720c98a48c77f2d49d375932b2867e793029e6337f1562522640e4f84203d2e'
  - 'telegram: desci0'
  - 'x(twitter): https://x.com/123olp'

