# .github/labeler.yml
# 为 actions/labeler 定义标签规则

# 文档相关的标签
documentation:
  - changed-files:
    - any-glob-to-any-file: ['i18n/**/*.md', 'README.md', 'CONTRIBUTING.md', 'LICENSE']

# CI/CD 工作流相关的标签
cicd:
  - changed-files:
    - any-glob-to-any-file: '.github/workflows/*'

# 提示词相关的标签
prompt:
  - changed-files:
    - any-glob-to-any-file: 'i18n/zh/prompts/**/*.md'

# 实战案例相关的标签
example:
  - changed-files:
    - any-glob-to-any-file: 'i18n/zh/documents/实战案例/**/*.md'